#include "studio/gfx/gfx.h"

#include <SDL3/SDL.h>

#include <cmath>
#include <vector>

namespace studio {
namespace {

// SDL3 geometry takes float colors. One conversion, used by every filled shape.
SDL_FColor fcolor(Color c) {
    return SDL_FColor{c.r / 255.0f, c.g / 255.0f, c.b / 255.0f, c.a / 255.0f};
}

// Segments per 90-degree corner. Six reads as round at the sizes chrome uses
// (8-12px radii) without spending vertices no one can see.
constexpr int kArcSegments = 6;

// Append the points of a rounded-rect perimeter, walking clockwise from the
// top-left corner's start. Shared by fill (fan) and stroke (two offset rings),
// so a filled panel and its outline trace the exact same path and cannot drift.
void rounded_perimeter(Rect b, float radius, std::vector<SDL_FPoint>& out) {
    float rad = radius;
    float half = 0.5f * (b.w < b.h ? b.w : b.h);
    if (rad > half) rad = half;
    if (rad < 0) rad = 0;

    // Corner centers, clockwise: TL, TR, BR, BL. Each arc sweeps 90 degrees.
    const float cx[4] = {b.x + rad, b.right() - rad, b.right() - rad, b.x + rad};
    const float cy[4] = {b.y + rad, b.y + rad, b.bottom() - rad, b.bottom() - rad};
    // Start angle of each corner arc, in radians (screen space, y down).
    const float start[4] = {static_cast<float>(M_PI), -static_cast<float>(M_PI_2), 0.0f,
                            static_cast<float>(M_PI_2)};

    for (int corner = 0; corner < 4; ++corner) {
        for (int s = 0; s <= kArcSegments; ++s) {
            float t = start[corner] + (static_cast<float>(M_PI_2) * s) / kArcSegments;
            out.push_back(SDL_FPoint{cx[corner] + std::cos(t) * rad, cy[corner] + std::sin(t) * rad});
        }
    }
}

}  // namespace

void Gfx::clear(Color c) {
    SDL_SetRenderDrawColor(r_, c.r, c.g, c.b, c.a);
    SDL_RenderClear(r_);
}

void Gfx::fill_rect(Rect box, Color c) {
    SDL_SetRenderDrawBlendMode(r_, SDL_BLENDMODE_BLEND);
    SDL_SetRenderDrawColor(r_, c.r, c.g, c.b, c.a);
    SDL_FRect fr{box.x, box.y, box.w, box.h};
    SDL_RenderFillRect(r_, &fr);
}

void Gfx::fill_rounded(Rect box, float radius, Color c) {
    std::vector<SDL_FPoint> ring;
    rounded_perimeter(box, radius, ring);
    if (ring.size() < 3) return;

    SDL_FColor col = fcolor(c);
    // Fan from the centroid. One center vertex, then the ring; triangles wrap
    // (center, i, i+1) around the whole perimeter including the closing edge.
    std::vector<SDL_Vertex> verts;
    verts.reserve(ring.size() + 1);
    SDL_Vertex center{};
    center.position = SDL_FPoint{box.x + box.w * 0.5f, box.y + box.h * 0.5f};
    center.color = col;
    verts.push_back(center);
    for (const auto& p : ring) {
        SDL_Vertex v{};
        v.position = p;
        v.color = col;
        verts.push_back(v);
    }

    std::vector<int> idx;
    idx.reserve(ring.size() * 3);
    const int n = static_cast<int>(ring.size());
    for (int i = 0; i < n; ++i) {
        idx.push_back(0);
        idx.push_back(1 + i);
        idx.push_back(1 + (i + 1) % n);
    }

    SDL_SetRenderDrawBlendMode(r_, SDL_BLENDMODE_BLEND);
    SDL_RenderGeometry(r_, nullptr, verts.data(), static_cast<int>(verts.size()), idx.data(),
                       static_cast<int>(idx.size()));
}

void Gfx::stroke_rounded(Rect box, float radius, float width, Color c) {
    if (width <= 0) return;
    std::vector<SDL_FPoint> outer, inner;
    rounded_perimeter(box, radius, outer);
    rounded_perimeter(box.inset(width), radius - width, inner);
    // The two rings are generated by the same routine with the same segment
    // count, so they are point-for-point parallel and a strip between them is
    // well defined.
    if (outer.size() != inner.size() || outer.size() < 3) return;

    SDL_FColor col = fcolor(c);
    std::vector<SDL_Vertex> verts;
    verts.reserve(outer.size() + inner.size());
    for (const auto& p : outer) {
        SDL_Vertex v{};
        v.position = p;
        v.color = col;
        verts.push_back(v);
    }
    for (const auto& p : inner) {
        SDL_Vertex v{};
        v.position = p;
        v.color = col;
        verts.push_back(v);
    }

    const int n = static_cast<int>(outer.size());
    std::vector<int> idx;
    idx.reserve(n * 6);
    for (int i = 0; i < n; ++i) {
        int o0 = i, o1 = (i + 1) % n;
        int i0 = n + i, i1 = n + (i + 1) % n;
        // Two triangles per segment forming the quad between outer and inner.
        idx.push_back(o0);
        idx.push_back(o1);
        idx.push_back(i1);
        idx.push_back(o0);
        idx.push_back(i1);
        idx.push_back(i0);
    }

    SDL_SetRenderDrawBlendMode(r_, SDL_BLENDMODE_BLEND);
    SDL_RenderGeometry(r_, nullptr, verts.data(), static_cast<int>(verts.size()), idx.data(),
                       static_cast<int>(idx.size()));
}

void Gfx::line(float x0, float y0, float x1, float y1, Color c) {
    SDL_SetRenderDrawBlendMode(r_, SDL_BLENDMODE_BLEND);
    SDL_SetRenderDrawColor(r_, c.r, c.g, c.b, c.a);
    SDL_RenderLine(r_, x0, y0, x1, y1);
}

void Gfx::debug_text(float x, float y, std::string_view s, Color c, float scale) {
    SDL_SetRenderScale(r_, scale, scale);
    SDL_SetRenderDrawColor(r_, c.r, c.g, c.b, c.a);
    // SDL's debug text is drawn in the current render scale's coordinate space,
    // so the position is divided back out to land where the caller asked.
    std::string z(s);
    SDL_RenderDebugText(r_, x / scale, y / scale, z.c_str());
    SDL_SetRenderScale(r_, 1.0f, 1.0f);
}

float Gfx::debug_text_width(std::string_view s, float scale) {
    // SDL's debug font is a fixed 8px cell per glyph.
    return static_cast<float>(s.size()) * 8.0f * scale;
}

void Gfx::output_size(int* w, int* h) const { SDL_GetCurrentRenderOutputSize(r_, w, h); }

}  // namespace studio
